### ISSUE TITLE
Making plugin and organization fields uneditable

### ISSUE THREAD

**Issue by FrankTN** [RUGSoftEng/2017-Hestia-Client#51]
It is possible to paste text in the plugin name and organization field when entering the required information.

**Comment by Feikoritsema** [comment]
I fixed this before we handed in the MVP, but wil fix it again if it is a problem now

**Comment by StefanEvanghelides** [comment]
After the meeting on Monday, we decided to change the Collection and Plugin fields from Text fields to a **bold** text. In this way, is will be clear for the user that those parts should be uneditable. It also removes the problem of copy-pasting into uneditable fields.

The others may still be Text fields.

**Comment by LarsHoldijk** [comment]
At which meeting was this decided? If we include these fields in the required info there is no reason to modify the JSON we send when the required info is requested. Since it is all pushed into one big HashMap again. 

I propose to show the collection and plugin name in some kind of title for the frame.

**Comment by StefanEvanghelides** [comment]
This issue was solved with the latest architecture. I believe it can closed.
