### ISSUE TITLE
Change getRequest tasks return type

### ISSUE THREAD

**Issue by FrankTN** [RUGSoftEng/2017-Hestia-Client#67]
The getRequest asynctasks currently return multiple types of lists, which requires the use of generics in the superclass. This is unnecessary, as both subclasses can just return a JSON object.

**Comment by StefanEvanghelides** [comment]
There is an issue with this. Getting the list of devices will not be a JsonObject, but a JsonArray. I can think of 2 possible solutions:

1. Make the return type a String, since the information retrieved from the server is in the form of a string (and if not, it can be easily converted to one). Then, process each string separately, according to our needs. This may lead to some duplicate code. Personally, I do not like this method.

2. Change the JsonArray to a JsonObject. The change is not necessarily difficult. Instead of
`[
  { device1...},
  { device2...},
  { device3...}
]`
we could have something like this
`{
  "devices": [
      { devices1...},
      { devices2...},
      { devices3...},
  ]
}`
I prefer this solution more than the other one. In this way, the Server will be consistent in sending JsonObjects

**Comment by LarsHoldijk** [comment]
I believe you could use a JSON primitive for both formats.

I still don't really get why you we should move a way from the generics though. The only downside of using generics in this case that I see is that we need to know exactly what the asynctask returns to cast it properly. This would still be the case when we return a JSON object, except that the deserialization is not as easy as casting.

**Comment by StefanEvanghelides** [comment]
It was changed to JsonElement, which allows for both JsonObject and JsonArray.
