### ISSUE TITLE
JSON object read by deserializer should correspond with object sent from server

### ISSUE THREAD

**Issue by FrankTN** [RUGSoftEng/2017-Hestia-Client#76]
While writing tests for the deserializer I noticed that there is an asymmetry between the naming of our fields and the JSON objects we receive. We should fix this together with the server team.
This is our current, internal representation of the Activator:
`{"id":1,"name":"TEST_SWITCH","state":{"rawState":true,"type":"TOGGLE"}}`

In particular, the activatorState is nested, which should be changed.

**Comment by StefanEvanghelides** [comment]
Can you give more details? What is the JSON object that the server sends?

**Comment by LarsHoldijk** [comment]
Nothing changed in the server API expect that the state is not longer a string but a Json primitive. So instead of  "true"  you just receive and send true.

Example1 :
You want to turn on a light, to do this the toggle of the light is switched to on. The client should send to the server the HTTP Post: 
        {"state": true}
This messages should be posted on the exact same place as previous version of the server, but now with strings for ids instead of and integer.

**Comment by StefanEvanghelides** [comment]
I believe it does now. Will close this issue. In case the problem persists, we shall reopen it.
